mixed-port: 7890
allow-lan: true
mode: rule
log-level: info

proxies:
  - name: "Tokyo-Hysteria2"
    type: hysteria2
    server: jty.jzxlm1314.qzz.io
    port: 29570
    password: 1b4f1d6e-40a0-4212-a38f-823628edaf9f
    alpn:
      - h3
    sni: jty.jzxlm1314.qzz.io
    up: "50 Mbps"
    down: "100 Mbps"

  - name: "Tokyo-Reality"
    type: vless
    server: jty.jzxlm1314.qzz.io
    port: 16557
    uuid: 1b4f1d6e-40a0-4212-a38f-823628edaf9f
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: jty.jzxlm1314.qzz.io
    reality-opts:
      public-key: JSQhBr1IYZQKHeTASitHDBWyWquBPxgNeAunBBzgx0M
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome